spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: libraryApp

  sql:
    init:
      mode: always # I'm just doing this for demo purposes

  mvc:
    hiddenmethod:
      filter:
        enabled: true